theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
mainSections = ["blog", "projects"]

enableRobotsTXT = true
summaryLength = 0
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
